#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# redirecting the homepage
# found at https://symfony.com/doc/current/routing/redirect_in_config.html
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /login
        permanent: true